#ifndef LIGHTNVR_VERSION_H
#define LIGHTNVR_VERSION_H

#define LIGHTNVR_VERSION_MAJOR 0
#define LIGHTNVR_VERSION_MINOR 10
#define LIGHTNVR_VERSION_PATCH 23
#define LIGHTNVR_VERSION_STRING "0.10.23"

#define LIGHTNVR_BUILD_DATE ""
#define LIGHTNVR_GIT_COMMIT ""

#endif // LIGHTNVR_VERSION_H
