#ifndef LIGHTNVR_VERSION_H
#define LIGHTNVR_VERSION_H

#define LIGHTNVR_VERSION_MAJOR 0
#define LIGHTNVR_VERSION_MINOR 26
#define LIGHTNVR_VERSION_PATCH 1
#define LIGHTNVR_VERSION_STRING "0.26.1"

#define LIGHTNVR_BUILD_DATE ""
#define LIGHTNVR_GIT_COMMIT ""

#endif // LIGHTNVR_VERSION_H
